force-app/main/default/objects/Rates__c/Rates__c.object-meta.xml
<CustomObject>
    <label>Rates</label>
    <nameField>
        <label>Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rates__c/fields/Currencies__c.field-meta.xml
<CustomField>
    <fullName>Currencies__c</fullName>
    <label>Currencies</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/bankOfCanadaTriggerHandler.cls
public with sharing class bankOfCanadaTriggerHandler implements Queueable, Database.AllowsCallouts {
    public static void execute(List<currencies__c> insertedCurrencies, QueueableContext ctx){
        try{
            List<String> fieldNames = bankOfCanadaHandler.currencySeparator(insertedCurrencies);

            HttpRequest req = new HttpRequest();
            req.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionId());
            req.setHeader('Content-Type', 'application/json');

            req.setEndpoint('https://empathetic-goat-jgesbg-dev-ed.trailblaze.my.salesforce.com/services/data/v66.0/composite');

            Map<String,SObject> body = new Map<String,SObject>();
            body.put('compositeRequest', body);


            req.setBody(body);

            List<HttpRequest> subRequests = new List<HttpRequest>();
            for(currencies__c coins : insertedCurrencies){
                HttpRequest sub = new HttpRequest();
                sub.setMethod('GET');
                sub.setEndpoint('https://empathetic-goat-jgesbg-dev-ed.trailblaze.my.salesforce.com/services/data/v66.0/tooling/sobjects/rates__c.FXCAD' + coins.name);
            }
        }
    }
    
    public static void toQueue(){
        bankOfCanadaCallout callout = new bankOfCanadaCallout();
        System.enqueueJob(callout);
        return;
    }
}